services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - weather_dashboard_network

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - weather_dashboard_network

networks:
  weather_dashboard_network:
    driver: bridge